/**
 * `userbatch/<termCode>.json` (TBD)
 *
 * Location (SSG static assets):
 * - `app/static/crawler/data/userbatch/<termCode>.json`
 *
 * This file is generated by crawler/CI and published alongside term snapshots.
 *
 * IMPORTANT:
 * - It is USER-AGNOSTIC. Do not include userId/password/cookie/batch membership of a specific account.
 * - It describes course-group-level batch/cohort rules keyed by our `groupKey` algorithm.
 */

export type UserBatchJson = {
	version: 1;
	generatedAt: number;
	termCode: string;
	source?: 'ci' | 'manual' | 'unknown';
	groups: Record<string, CourseGroupUserBatch>;
};

export type CourseGroupUserBatch = {
	groupKey: string;
	courseIds?: string[];
	/**
	 * Human-readable restrictions summary (raw). Parser/UI may display it,
	 * but must not infer user eligibility without user profile signals.
	 */
	rulesText?: string[];
	/**
	 * TBD: structured batch/cohort rules.
	 * Example: allowed cohorts, retake-only, prerequisite tags, etc.
	 */
	tbd?: Record<string, unknown>;
};

